# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-21 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_buddy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='users',
            field=models.ManyToManyField(related_name='trips', to='trip_buddy.User'),
        ),
    ]
