# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-21 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip_buddy', '0002_auto_20190621_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='creators',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='create_trips', to='trip_buddy.User'),
            preserve_default=False,
        ),
    ]
