# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-22 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_buddy', '0003_trip_creators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='users',
        ),
        migrations.AddField(
            model_name='trip',
            name='travelers',
            field=models.ManyToManyField(related_name='travelers', to='trip_buddy.User'),
        ),
    ]
