# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-22 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_buddy', '0004_auto_20190622_0335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='creators',
            new_name='user_creates',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='travelers',
        ),
        migrations.AddField(
            model_name='trip',
            name='user_travels',
            field=models.ManyToManyField(related_name='travel_trips', to='trip_buddy.User'),
        ),
    ]
